// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJLHn5duckojaA4yIb_UOwZTvaxBv2iHY',
    appId: '1:1048337037888:web:f787b85526f19a1511bda5',
    messagingSenderId: '1048337037888',
    projectId: 'ascend-441b7',
    authDomain: 'ascend-441b7.firebaseapp.com',
    storageBucket: 'ascend-441b7.firebasestorage.app',
    measurementId: 'G-TERGF51VEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLFE58eeqEFRIWE_FRSnSSH_Gv1NgVNb0',
    appId: '1:1048337037888:android:4af89ebc9cd0500911bda5',
    messagingSenderId: '1048337037888',
    projectId: 'ascend-441b7',
    storageBucket: 'ascend-441b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZaVQKVxmDgVpJuYPGxFVy8uQPkyYNZ20',
    appId: '1:1048337037888:ios:fc6f3f662e2cc80611bda5',
    messagingSenderId: '1048337037888',
    projectId: 'ascend-441b7',
    storageBucket: 'ascend-441b7.firebasestorage.app',
    iosBundleId: 'com.newdomain.ascend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZaVQKVxmDgVpJuYPGxFVy8uQPkyYNZ20',
    appId: '1:1048337037888:ios:80f285c3893d6e3611bda5',
    messagingSenderId: '1048337037888',
    projectId: 'ascend-441b7',
    storageBucket: 'ascend-441b7.firebasestorage.app',
    iosBundleId: 'com.example.findo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJLHn5duckojaA4yIb_UOwZTvaxBv2iHY',
    appId: '1:1048337037888:web:7a73d75f1e591ec411bda5',
    messagingSenderId: '1048337037888',
    projectId: 'ascend-441b7',
    authDomain: 'ascend-441b7.firebaseapp.com',
    storageBucket: 'ascend-441b7.firebasestorage.app',
    measurementId: 'G-5G0XN77BVD',
  );
}
